[project]
name = "quantduck"
version = "0.1.24"
description = "A Python package for quantitative analysis"
requires-python = ">=3.8,<3.12"
dependencies = [
    "psycopg2-binary>=2.9.0",
    "pytz",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
