[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quantduck"
version = "0.1.3"
description = "A quantitative analysis library"
requires-python = ">=3.6"
dependencies = [
    "psycopg2-binary",
    "pytz",
    "pandas",
]
